[build]
  base = "/frontend/"
  command = "pnpm run build"
  publish = "dist/frontend/"

[images]
  remote_images = ["https://res.cloudinary.com/dd8ep4kjo/image/upload/.*"]


[[redirects]]
  from = "/*"
  to = "/browser/index.csr.html"
  status = 200
